import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Roboto_Mono, Open_Sans } from "next/font/google";
import Providers from "./providers/Providers";
import { Toaster } from "react-hot-toast";
const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  //👇 Add variable to our object
  variable: "--font-opensans",
});
const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-mono",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${openSans.variable} ${robotoMono.variable} font-sans bg-background`}
      >
        <Providers>
          <ThemeProvider>
            <div className="flex flex-col  h-[1px] relative overflow-y-auto overflow-x-hidden max-h-dvh w-full min-h-dvh">
              {children}
            </div>
            <Toaster position="bottom-center" />
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
